### ISSUE TITLE
Running with coverage enabled bypasses babel transforms

### ISSUE THREAD

**Issue by memoryhole** [rogeliog/jest-runner-mocha#13]
It looks like jest-runner-mocha is configured to intentionally bypass your babelrc when running coverage. This is resulting in test failures for my project. When I flip this flag to true everything appears to work fine. Do you remember the motivation to have set it to false? 

https://github.com/rogeliog/jest-runner-mocha/blob/322a6657909a637e0987aa39300fd0e8d0003111/src/utils/setupCollectCoverage.js#L32

**Comment by rogeliog** [comment]
Hi!
Thanks for reporting, I originally got it from
https://github.com/facebook/jest/blob/master/packages/jest-runtime/src/script_transformer.js#L152-L169

The more I think about it, I think you might be right that this is not needed, which error are you getting when running it with `babel: false`, are they syntax errors because it is not compiled or is it something else?

**Comment by rogeliog** [comment]
Closed via #15
